#!/bin/bash

set -e

key=`config-get aws_key`
secret=`config-get aws_secret`
release=`config-get release`
pubkey=`config-get pubkey`

SSHDIR=/home/ubuntu/.juju/ssh

if [[ ! -d $SSHDIR ]]
then
    mkdir -p $SSHDIR
fi

PRIVKEY="${SSHDIR}/juju_id_rsa"
config-get privkey > $PRIVKEY
chmod 600 $PRIVKEY

echo $pubkey > "${SSHDIR}/juju_id_rsa.pub"

echo "Release: ${release} Creds:${key}:${secret}"
